# Create a clean, minimal image
FROM eclipse-temurin:21@sha256:85f00967bcc624fc19fa9c2cf124ea426a5363898e267141726f31f358c2e14b AS typed-pid-maker
LABEL maintainer="webmaster@datamanager.kit.edu"
LABEL stage=run

ENV REPO_PORT=8090

RUN mkdir -p /app/config
COPY /build/libs/TypedPIDMaker*.jar /app/TypedPIDMaker.jar
COPY config/application-docker.properties /app/config/application-default.properties
EXPOSE ${REPO_PORT}
WORKDIR /app/
ENTRYPOINT ["./TypedPIDMaker.jar"]
