# Create a clean, minimal image
FROM eclipse-temurin:21 AS typed-pid-maker
LABEL maintainer="webmaster@datamanager.kit.edu"
LABEL stage=run

ENV REPO_PORT=8090

ARG SERVICE_DIRECTORY=/typid
RUN mkdir -p ${SERVICE_DIRECTORY}/config
COPY /build/libs/TypedPIDMaker*.jar ${SERVICE_DIRECTORY}/TypedPIDMaker.jar
COPY /config/* ${SERVICE_DIRECTORY}/config/
EXPOSE ${REPO_PORT}
CMD ["/typid/TypedPIDMaker.jar"]
