# Create a clean, minimal image
FROM eclipse-temurin:21@sha256:ec2005c536f3661c6ef1253292c9c623e582186749a3ef2ed90903d1aaf74640 AS typed-pid-maker
LABEL maintainer="webmaster@datamanager.kit.edu"
LABEL stage=run

ENV REPO_PORT=8090

RUN mkdir -p /app/config
COPY /build/libs/TypedPIDMaker*.jar /app/TypedPIDMaker.jar
COPY config/application-docker.properties /app/config/application-default.properties
EXPOSE ${REPO_PORT}
WORKDIR /app/
ENTRYPOINT ["./TypedPIDMaker.jar"]
