FROM eclipse-temurin:21@sha256:1f79c73404fb0cccf9a3459eda22892f368d994b1028d6fb1ae871c1f49749a6 AS build-typid
LABEL maintainer="webmaster@datamanager.kit.edu"
LABEL stage=build
RUN mkdir -p /app/
WORKDIR /app/
COPY . .
RUN ./gradlew build -x test --stacktrace && \
    cp build/libs/TypedPIDMaker*.jar ./


# Create a clean, minimal image
FROM eclipse-temurin:21@sha256:1f79c73404fb0cccf9a3459eda22892f368d994b1028d6fb1ae871c1f49749a6 AS typed-pid-maker
LABEL maintainer="webmaster@datamanager.kit.edu"
LABEL stage=run

ENV REPO_PORT=8090

RUN mkdir -p /app/config && mkdir -p /data/
COPY --from=build-typid /app/TypedPIDMaker*.jar /app/TypedPIDMaker.jar
COPY config/application-docker.properties /app/config/application-default.properties
EXPOSE ${REPO_PORT}
WORKDIR /app/
ENTRYPOINT ["./TypedPIDMaker.jar"]
