# Create and publish a Docker image on GitHub
# References:
# - https://docs.docker.com/build/ci/github-actions/multi-platform/
name: Create and publish a Docker image

# Configures this workflow to run every time a change
# is pushed to the 'main' branch.
on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
      - '*-v*'

# Defines two custom environment variables for the workflow.
# These are used for the Container registry domain, and a
# name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kit-data-manager/Typed-PID-Maker # repo name != app name in our case!
  jdk: 25
  distro: 'temurin'
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

# Two jobs for creating and pushing Docker image
# - build-and-push-image -> triggered by commits on main and tagging with semantic version (e.g.: v1.2.3)
# - build-and-push-image-of-branch -> triggered by tags matching '*-v*' (e.g.: Version_1-v1.2.3)
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref_name, '-v') == failure() }}
    # Sets the permissions granted to the `GITHUB_TOKEN`
    # for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up openJDK version
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.jdk }}
          distribution: ${{ env.distro }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6

      - name: Build and Test with Gradle
        run: ./gradlew -Dprofile=verbose build

      - name: Set up Docker
        uses: docker/setup-docker-action@b2189fbf2a6592b51fee7cdd93ee2bfaeba733db # v5
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      # Uses the `docker/login-action` action to log in to the Container
      # registry using the account and password that will publish the packages.
      # Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Add support for more platforms with QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about)
      # to extract tags and labels that will be applied to the specified image.
      # The `id` "meta" allows the output of this step to be referenced in a
      # subsequent step. The `images` value provides the base name for the tags
      # and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=Typed-PID-Maker
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./docker/Dockerfile-reuse-local-build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: ${{ env.DOCKER_PLATFORMS }}

  build-and-push-image-of-branch:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, '-v')
    # Sets the permissions granted to the `GITHUB_TOKEN`
    # for the actions in this job.
    permissions:
      contents: read
      packages: write
      #
    steps:
      - name: Split first part
        env:
          TAG: ${{ github.ref_name }}
        id: split
        run: echo "branch=${TAG%-v*}" >> $GITHUB_OUTPUT

      - name: Test variable
        run: |
          echo ${{ steps.split.outputs.branch }}

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up openJDK version
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.jdk }}
          distribution: ${{ env.distro }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6

      - name: Build and Test with Gradle
        run: ./gradlew -Dprofile=verbose build

      - name: Set up Docker
        uses: docker/setup-docker-action@b2189fbf2a6592b51fee7cdd93ee2bfaeba733db # v5
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      # Uses the `docker/login-action` action to log in to the Container
      # registry using the account and password that will publish the packages.
      # Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Add support for more platforms with QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about)
      # to extract tags and labels that will be applied to the specified image.
      # The `id` "meta" allows the output of this step to be referenced in a
      # subsequent step. The `images` value provides the base name for the tags
      # and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta-branch
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{steps.split.outputs.branch}}
          labels: |
            org.opencontainers.image.title=Typed-PID-Maker
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./docker/Dockerfile-reuse-local-build
          push: true
          tags: ${{ steps.meta-branch.outputs.tags }}
          labels: ${{ steps.meta-branch.outputs.labels }}
          annotations: ${{ steps.meta-branch.outputs.annotations }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
